# This file was generated by GoReleaser. DO NOT EDIT.
cask "tailout" do
  name "tailout"
  desc "Spawn an exit node for your tailnet anywhere with Tailout"
  homepage "https://github.com/lucacome/tailout"
  version "1.0.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "tailout"

  on_macos do
    on_intel do
      url "https://github.com/lucacome/tailout/releases/download/v#{version}/tailout_#{version}_darwin_amd64.tar.gz"
      sha256 "40c3aec30edf67c77405608fb921fbd6527c155a37b8129a95f8a366a8acb877"
    end
    on_arm do
      url "https://github.com/lucacome/tailout/releases/download/v#{version}/tailout_#{version}_darwin_arm64.tar.gz"
      sha256 "748667fdebb8a8b89e7d6f9fcba7eb779f16186f9a2f1a69d298195e03a223cc"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/lucacome/tailout/releases/download/v#{version}/tailout_#{version}_linux_amd64.tar.gz"
      sha256 "27fa68b27fdbb9e77745b800724eba76248446610b436836de2a7a821ef53a23"
    end
    on_arm do
      url "https://github.com/lucacome/tailout/releases/download/v#{version}/tailout_#{version}_linux_arm64.tar.gz"
      sha256 "8e1b3b41aae54590605eddbd99071c75ca6fd6d71e88fb9aa6b8ac452a70ea5e"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/tailout"]
    end
  end

  # No zap stanza required
end
